### ISSUE TITLE
This project seems abandoned

### ISSUE THREAD

**Issue by noah1gamble** [cwtools/cwtools-vscode#66]
The lack of updates on this is extremely disappointing, I use this every single day and there are multiple issues that make developing really frustrating such as false-positives, non-added effects/triggers/etc.

What is going on with the progress for CWTools?

**Comment by IhateTrains** [comment]
The project is open source. How about you submit improvements instead of making entitled comments?

**Comment by tboby** [comment]
This project is all but complete.

This repository is the cwtools VS Code extension, which is stable and only really needs to be updated when the underlying server changes.

www.github.com/cwtools/cwtools is the core language server, which is basically complete for all scripting language features in games up until hoi4. Games from Imperator onwards are fairly well supported although there a few gaps.

**I suspect what you're referring to is the maintenance of game specific rules**. I don't have time to maintain them, and as I've never actually made a mod for Paradox games I'm not the most appropriate person. Instead, experienced modders who find the extension helpful curate the rules, which is great because they actually know how it should work :)

I don't know which game you're having trouble with, but each repository explains how to contribute and detailed descriptions of how the rules work can be found here: https://github.com/cwtools/cwtools/wiki/.cwt-config-file-guidance

The rules repositories can be found here:

www.github.com/cwtools/cwtools-stellaris-config

www.github.com/cwtools/cwtools-hoi4-config

www.github.com/cwtools/cwtools-ck3-config

www.github.com/cwtools/cwtools-eu4-config
